server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/leyou
eureka:
  client:
    service-url:
      defaultZone: 127.0.0.1:10086/eureka
mybatis:
  type-aliases-package: com.leyou.user.pojo
